### PR TITLE
Requirement simplification and updates

### PR DESCRIPTION
**Pull request by adonm**
Adjusting requirements to make more compatible with other packages like msticpy and bumping version # to 0.1.8

### CODE REVIEW

**Comment by streanger** [comment]
hey @adonm!
I knew about this problems, but I was waiting with my other local changes to be commited. I'll get into it in the beginning of the next week

**Comment by streanger** [comment]
@adonm hey again!
I've made some changes and applied it here https://github.com/streanger/abuseipdb-wrapper/commit/98da4f659cd2065420960dccea2f91d4e2e6b8bd. I also bumped [pypi version to 0.1.8 ](https://pypi.org/project/abuseipdb-wrapper/)

First thing you might be interested in is to change param `API_KEY` (uppercase) to `api_key` (lowercase) as in the code below:
```python
from abuseipdb_wrapper import AbuseIPDB
API_KEY = 'YOUR_API_KEY'
abuse = AbuseIPDB(api_key=API_KEY)
```
Second thing is requirements. I adjusted them using `>=` to meet current and latest versions of packages.
https://github.com/streanger/abuseipdb-wrapper/blob/7d4771e104825986983c4641a250cab675f4722e/setup.py#L18-L27

Please give a try and let me know if it fit your needs. I'm gonna fix one more bug soon, so I'm open to any changes proposal

**Comment by adonm** [comment]
Hi @streanger - I've tested and this is great for our needs =). Note I saw a small bug in CI for the import related to the `tor_enrich` module but not an issue for us with interactive use:

https://github.com/streanger/abuseipdb-wrapper/blob/main/abuseipdb_wrapper/tor_enrich.py#L11 - sometimes (e.g. in a CI job) sys.stdout.encoding can be none which causes base import to fail.

Thanks again!

**Comment by streanger** [comment]
> https://github.com/streanger/abuseipdb-wrapper/blob/main/abuseipdb_wrapper/tor_enrich.py#L11 - sometimes (e.g. in a CI job) sys.stdout.encoding can be none which causes base import to fail.

thanks for pointing this out. It was meant to check if specific terminal handles encoding of this character. However it didn't work at all. And in the next version (`0.1.9`) I removed imports related to `tor_enrich` due to existing of `isTor` field supported by abuse api. So I hope for now it shouldn't be a problem at all.

image

---

As of yesterday I released version `0.2.0`, where I get rid of `pandas` dependency, in place of custom export functions. I realized that some packages are too heavy, and use of single function is not enough in that case. I think that last changes shouldn't affect other important parts of code. At least tests are passing :)
And for now I'm not planning any other releases until someone will ask for update and I find time for it.

Thanks for your interest!

**Pull request closed without merging**
